### ISSUE TITLE
stick drift

### ISSUE THREAD

**Issue by reekid704** [Kttra/Stick-Drift-Fix#2]
right sick goes up when not touching it

**Comment by Kttra** [comment]
Stick drift varies between controllers due to differences in manufacturing and usage. The threshold value in the script determines the sensitivity range within which stick drift is corrected. I've increased this threshold to 80, which should solve the issue for most people.

Since drift can be more severe in some controllers, I recommend adjusting the threshold values to suit your specific controller. This ensures optimal performance and effectively eliminates drift.
